spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/jobsdb
    driver-class-name: org.postgresql.Driver
    username: jobuser
    password: jobpass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
